branch-defaults:
  main:
    environment: decathlon-postural-health-backend
    group_suffix: null
global:
  application_name: decathlon-postural-health
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application

